# Official UniVLA finetuned on LIBERO-goal
script: "src/vla_eval/model_servers/semtok_vla.py"
args:
  model_path: /scratch/e1816a02/semtok_vla/univla-sft-libero/univla-libero-goal
  unnorm_key: libero_goal_no_noops
  use_latent: true
  action_decoder_path: /scratch/e1816a02/semtok_vla/univla-sft-libero/univla-libero-goal/action_decoder.pt
  window_size: 12
  center_crop: true
  semtok_vla_path: /scratch/e1816a02/semtok_vla
  chunk_size: 1
  port: 8000
